site_name: hhhjyz的笔记本
site_url: https://hhhjyz.github.io
repo_name: hhhjyz/note
repo_url: https://github.com/hhhjyz/hhhjyz.github.io
site_description: hhhjyz的笔记本
copyright: Copyright &copy; hhhjyz/All Rights Reserved.
site_author: hhhjyz

theme: 
    favicon: image/head.jpg
    logo: image/head.jpg
    name: material
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: slate
          accent: light
          toggle:
              icon: material/toggle-switch
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: default
          accent: cyan
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to light mode
    language: zh
    font: false
    features:
        - content.code.annotate
        - navigation.tracking
        - navigation.tabs
        - navigation.indexes
        - navigation.top


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true


plugins: 
    - search

extra_css:
    - css/round.css
    - css/extra.css
    - https://fonts.loli.net/css2?family=Noto+Serif+SC&display=swap
    - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
    - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
    - javascripts/mathjax.js
    - javascripts/katex.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
    - https://unpkg.com/katex@0/dist/katex.min.js
    - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

nav: 
    - Home: index.md
    - 课程笔记:
        - 高级数据结构与算法分析:
            - Review: note/courses/ads/Final.md
            - Lec8 Dynamic Programming: note/courses/ads/Lec8.md
            - Lec9 Greedy Algorithm: note/courses/ads/Lec 9.md
            - Lec10 NP-Completeness: note/courses/ads/Lec 10.md
            - Lec11 Approximation: note/courses/ads/Lec11.md
            - Lec12 Local Search: note/courses/ads/Lec 12.md
            - Lec14 Parallel Algorithm: note/courses/ads/Lec14.md
        - 计算机组成:
            - Chapter 1: note/courses/computer_organization/Chapter 1.md
            - Chapter 2: note/courses/computer_organization/Chapter 2.md
            - Chapter 4: note/courses/computer_organization/Chapter 4.md
            - Chapter 5: note/courses/computer_organization/Chapter 5.md
            - Chapter 6: note/courses/computer_organization/Chapter 6.md
        - 大学物理实验: note/courses/physics/大物实验期末复习.md
        - 数据库系统: 
            - Chpater 1: note/courses/database system/chaper 1 Introduction.md
            - Chapter 2: note/courses/database system/Chapter 2 Relational Modeling.md
            - Chapter 3: note/courses/database system/Chapter 3.md
            - Chapter 4: note/courses/database system/Chapter 4.md
            - Chapter 5: note/courses/database system/Chapter 5.md
        - 计算机体系结构:
            - Chapter 1: note/courses/Computer Architecture/Chapter 1 Fundamentals of computer design.md
            - Chapter 2: note/courses/Computer Architecture/Chapter 2.md
            - Chapter 3: note/courses/Computer Architecture/Chapter 3.md
            - Chapter 4: note/courses/Computer Architecture/Chapter 4.md
            - Chapter 5: note/courses/Computer Architecture/Chapter 5.md
        - 人工智能:
            - Chapter 2: note/courses/AI/Chapter 2.md
            - Chapter 3: note/courses/AI/Chapter 3.md
            - Chapter 4: note/courses/AI/Chapter 4.md
            - Chapter 5: note/courses/AI/Chapter 5.md
            - Chapter 6: note/courses/AI/Chapter 6.md

        - 面向对象程序设计:
            - Lec8: note/courses/OOP/Lecture 8 Stream.md
            - Lec9: note/courses/OOP/Lecture 9 Exception.md

    - 自学:
        - EECS498-005:
            - Image Classification: note/self-study/EECS498/Lec2 Image Classification.md
            - Linear Classifiers: note/self-study/EECS498/Lec3 Linear Classifiers.md
            - Optimization: note/self-study/EECS498/Lec4 Optimization.md
            - Neural Network: note/self-study/EECS498/Lec5 Neural Network.md
            - Backpropagation: note/self-study/EECS498/Lec6 Backpropagation.md
            - CNN Architecture: note/self-study/EECS498/Lec8 CNN Architectures.md
            - Hardware and Software: note/self-study/EECS498/Lec9 Hardware and Software.md
            - Training 1: note/self-study/EECS498/Lec10 Training 1.md
            - Training 2: note/self-study/EECS498/Lec11 Training 2.md
            - Recurrent Neural Networks: note/self-study/EECS498/Lec12 Recurrent Neural Networks.md
            - Attention: note/self-study/EECS498/Lec13 Attention.md
            - Visualizing and Understanding: note/self-study/EECS498/Lec14 Visualizing and Understanding.md
            - Object Detection: note/self-study/EECS498/Lec15 Object Detection.md
            - Detection and Segmentation: note/self-study/EECS498/Lec16 Detection and Segmentation.md
            - 3D Vision: note/self-study/EECS498/Lec17 3D Vision.md
        - 工具:
            - conda: note/self-study/tools/conda.md
    - ZJU工具: use.md